/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyPolicyRouteImport } from './routes/warranty-policy'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as RoomSolutionsRouteImport } from './routes/room-solutions'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProofAndTrustRouteImport } from './routes/proof-and-trust'
import { Route as ProductUseCasesRouteImport } from './routes/product-use-cases'
import { Route as ProductRegistrationRouteImport } from './routes/product-registration'
import { Route as ProbioticAirPurificationRouteImport } from './routes/probiotic-air-purification'
import { Route as ProSubscriptionRouteImport } from './routes/pro-subscription'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as OrderHistoryRouteImport } from './routes/order-history'
import { Route as NurseryRouteImport } from './routes/nursery'
import { Route as MoldAndAllergensRouteImport } from './routes/mold-and-allergens'
import { Route as ManageSubscriptionRouteImport } from './routes/manage-subscription'
import { Route as HvacApplicationsRouteImport } from './routes/hvac-applications'
import { Route as HvacRouteImport } from './routes/hvac'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HealthBenefitsRouteImport } from './routes/health-benefits'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as EducationRouteImport } from './routes/education'
import { Route as DormRouteImport } from './routes/dorm'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompetitiveExclusionRouteImport } from './routes/competitive-exclusion'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BetterairRebrandRouteImport } from './routes/betterair-rebrand'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AffiliateSignupRouteImport } from './routes/affiliate-signup'
import { Route as AffiliateDashboardRouteImport } from './routes/affiliate-dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CompareUvcRouteImport } from './routes/compare.uvc'
import { Route as CompareHepaRouteImport } from './routes/compare.hepa'
import { Route as CompareChemicalFreshenersRouteImport } from './routes/compare.chemical-fresheners'
import { Route as CompareBioHealingRouteImport } from './routes/compare.bio-healing'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AffIdRouteImport } from './routes/aff.$id'

const WarrantyPolicyRoute = WarrantyPolicyRouteImport.update({
  id: '/warranty-policy',
  path: '/warranty-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSolutionsRoute = RoomSolutionsRouteImport.update({
  id: '/room-solutions',
  path: '/room-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofAndTrustRoute = ProofAndTrustRouteImport.update({
  id: '/proof-and-trust',
  path: '/proof-and-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductUseCasesRoute = ProductUseCasesRouteImport.update({
  id: '/product-use-cases',
  path: '/product-use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRegistrationRoute = ProductRegistrationRouteImport.update({
  id: '/product-registration',
  path: '/product-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbioticAirPurificationRoute =
  ProbioticAirPurificationRouteImport.update({
    id: '/probiotic-air-purification',
    path: '/probiotic-air-purification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProSubscriptionRoute = ProSubscriptionRouteImport.update({
  id: '/pro-subscription',
  path: '/pro-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderHistoryRoute = OrderHistoryRouteImport.update({
  id: '/order-history',
  path: '/order-history',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseryRoute = NurseryRouteImport.update({
  id: '/nursery',
  path: '/nursery',
  getParentRoute: () => rootRouteImport,
} as any)
const MoldAndAllergensRoute = MoldAndAllergensRouteImport.update({
  id: '/mold-and-allergens',
  path: '/mold-and-allergens',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSubscriptionRoute = ManageSubscriptionRouteImport.update({
  id: '/manage-subscription',
  path: '/manage-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacApplicationsRoute = HvacApplicationsRouteImport.update({
  id: '/hvac-applications',
  path: '/hvac-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacRoute = HvacRouteImport.update({
  id: '/hvac',
  path: '/hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthBenefitsRoute = HealthBenefitsRouteImport.update({
  id: '/health-benefits',
  path: '/health-benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DormRoute = DormRouteImport.update({
  id: '/dorm',
  path: '/dorm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitiveExclusionRoute = CompetitiveExclusionRouteImport.update({
  id: '/competitive-exclusion',
  path: '/competitive-exclusion',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BetterairRebrandRoute = BetterairRebrandRouteImport.update({
  id: '/betterair-rebrand',
  path: '/betterair-rebrand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateSignupRoute = AffiliateSignupRouteImport.update({
  id: '/affiliate-signup',
  path: '/affiliate-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDashboardRoute = AffiliateDashboardRouteImport.update({
  id: '/affiliate-dashboard',
  path: '/affiliate-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareUvcRoute = CompareUvcRouteImport.update({
  id: '/compare/uvc',
  path: '/compare/uvc',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareHepaRoute = CompareHepaRouteImport.update({
  id: '/compare/hepa',
  path: '/compare/hepa',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareChemicalFreshenersRoute =
  CompareChemicalFreshenersRouteImport.update({
    id: '/compare/chemical-fresheners',
    path: '/compare/chemical-fresheners',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareBioHealingRoute = CompareBioHealingRouteImport.update({
  id: '/compare/bio-healing',
  path: '/compare/bio-healing',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AffIdRoute = AffIdRouteImport.update({
  id: '/aff/$id',
  path: '/aff/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/affiliate-signup': typeof AffiliateSignupRoute
  '/auth': typeof AuthRoute
  '/betterair-rebrand': typeof BetterairRebrandRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/competitive-exclusion': typeof CompetitiveExclusionRoute
  '/contact': typeof ContactRoute
  '/dorm': typeof DormRoute
  '/education': typeof EducationRoute
  '/embed': typeof EmbedRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/health-benefits': typeof HealthBenefitsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/hvac': typeof HvacRoute
  '/hvac-applications': typeof HvacApplicationsRoute
  '/manage-subscription': typeof ManageSubscriptionRoute
  '/mold-and-allergens': typeof MoldAndAllergensRoute
  '/nursery': typeof NurseryRoute
  '/order-history': typeof OrderHistoryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/pro-subscription': typeof ProSubscriptionRoute
  '/probiotic-air-purification': typeof ProbioticAirPurificationRoute
  '/product-registration': typeof ProductRegistrationRoute
  '/product-use-cases': typeof ProductUseCasesRoute
  '/proof-and-trust': typeof ProofAndTrustRoute
  '/research': typeof ResearchRoute
  '/room-solutions': typeof RoomSolutionsRoute
  '/safety': typeof SafetyRoute
  '/shop': typeof ShopRoute
  '/solutions': typeof SolutionsRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/warranty-policy': typeof WarrantyPolicyRoute
  '/aff/$id': typeof AffIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/compare/bio-healing': typeof CompareBioHealingRoute
  '/compare/chemical-fresheners': typeof CompareChemicalFreshenersRoute
  '/compare/hepa': typeof CompareHepaRoute
  '/compare/uvc': typeof CompareUvcRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/affiliate-signup': typeof AffiliateSignupRoute
  '/auth': typeof AuthRoute
  '/betterair-rebrand': typeof BetterairRebrandRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/competitive-exclusion': typeof CompetitiveExclusionRoute
  '/contact': typeof ContactRoute
  '/dorm': typeof DormRoute
  '/education': typeof EducationRoute
  '/embed': typeof EmbedRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/health-benefits': typeof HealthBenefitsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/hvac': typeof HvacRoute
  '/hvac-applications': typeof HvacApplicationsRoute
  '/manage-subscription': typeof ManageSubscriptionRoute
  '/mold-and-allergens': typeof MoldAndAllergensRoute
  '/nursery': typeof NurseryRoute
  '/order-history': typeof OrderHistoryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/pro-subscription': typeof ProSubscriptionRoute
  '/probiotic-air-purification': typeof ProbioticAirPurificationRoute
  '/product-registration': typeof ProductRegistrationRoute
  '/product-use-cases': typeof ProductUseCasesRoute
  '/proof-and-trust': typeof ProofAndTrustRoute
  '/research': typeof ResearchRoute
  '/room-solutions': typeof RoomSolutionsRoute
  '/safety': typeof SafetyRoute
  '/shop': typeof ShopRoute
  '/solutions': typeof SolutionsRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/warranty-policy': typeof WarrantyPolicyRoute
  '/aff/$id': typeof AffIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/compare/bio-healing': typeof CompareBioHealingRoute
  '/compare/chemical-fresheners': typeof CompareChemicalFreshenersRoute
  '/compare/hepa': typeof CompareHepaRoute
  '/compare/uvc': typeof CompareUvcRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/affiliate-dashboard': typeof AffiliateDashboardRoute
  '/affiliate-signup': typeof AffiliateSignupRoute
  '/auth': typeof AuthRoute
  '/betterair-rebrand': typeof BetterairRebrandRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/competitive-exclusion': typeof CompetitiveExclusionRoute
  '/contact': typeof ContactRoute
  '/dorm': typeof DormRoute
  '/education': typeof EducationRoute
  '/embed': typeof EmbedRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/health-benefits': typeof HealthBenefitsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/hvac': typeof HvacRoute
  '/hvac-applications': typeof HvacApplicationsRoute
  '/manage-subscription': typeof ManageSubscriptionRoute
  '/mold-and-allergens': typeof MoldAndAllergensRoute
  '/nursery': typeof NurseryRoute
  '/order-history': typeof OrderHistoryRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/pro-subscription': typeof ProSubscriptionRoute
  '/probiotic-air-purification': typeof ProbioticAirPurificationRoute
  '/product-registration': typeof ProductRegistrationRoute
  '/product-use-cases': typeof ProductUseCasesRoute
  '/proof-and-trust': typeof ProofAndTrustRoute
  '/research': typeof ResearchRoute
  '/room-solutions': typeof RoomSolutionsRoute
  '/safety': typeof SafetyRoute
  '/shop': typeof ShopRoute
  '/solutions': typeof SolutionsRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/warranty-policy': typeof WarrantyPolicyRoute
  '/aff/$id': typeof AffIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/compare/bio-healing': typeof CompareBioHealingRoute
  '/compare/chemical-fresheners': typeof CompareChemicalFreshenersRoute
  '/compare/hepa': typeof CompareHepaRoute
  '/compare/uvc': typeof CompareUvcRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/affiliate-dashboard'
    | '/affiliate-signup'
    | '/auth'
    | '/betterair-rebrand'
    | '/blog'
    | '/case-studies'
    | '/competitive-exclusion'
    | '/contact'
    | '/dorm'
    | '/education'
    | '/embed'
    | '/faq'
    | '/glossary'
    | '/health-benefits'
    | '/how-it-works'
    | '/hvac'
    | '/hvac-applications'
    | '/manage-subscription'
    | '/mold-and-allergens'
    | '/nursery'
    | '/order-history'
    | '/payment-success'
    | '/privacy'
    | '/pro-subscription'
    | '/probiotic-air-purification'
    | '/product-registration'
    | '/product-use-cases'
    | '/proof-and-trust'
    | '/research'
    | '/room-solutions'
    | '/safety'
    | '/shop'
    | '/solutions'
    | '/subscription'
    | '/support'
    | '/terms'
    | '/videos'
    | '/warranty-policy'
    | '/aff/$id'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/compare/bio-healing'
    | '/compare/chemical-fresheners'
    | '/compare/hepa'
    | '/compare/uvc'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/affiliate-dashboard'
    | '/affiliate-signup'
    | '/auth'
    | '/betterair-rebrand'
    | '/blog'
    | '/case-studies'
    | '/competitive-exclusion'
    | '/contact'
    | '/dorm'
    | '/education'
    | '/embed'
    | '/faq'
    | '/glossary'
    | '/health-benefits'
    | '/how-it-works'
    | '/hvac'
    | '/hvac-applications'
    | '/manage-subscription'
    | '/mold-and-allergens'
    | '/nursery'
    | '/order-history'
    | '/payment-success'
    | '/privacy'
    | '/pro-subscription'
    | '/probiotic-air-purification'
    | '/product-registration'
    | '/product-use-cases'
    | '/proof-and-trust'
    | '/research'
    | '/room-solutions'
    | '/safety'
    | '/shop'
    | '/solutions'
    | '/subscription'
    | '/support'
    | '/terms'
    | '/videos'
    | '/warranty-policy'
    | '/aff/$id'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/compare/bio-healing'
    | '/compare/chemical-fresheners'
    | '/compare/hepa'
    | '/compare/uvc'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/affiliate-dashboard'
    | '/affiliate-signup'
    | '/auth'
    | '/betterair-rebrand'
    | '/blog'
    | '/case-studies'
    | '/competitive-exclusion'
    | '/contact'
    | '/dorm'
    | '/education'
    | '/embed'
    | '/faq'
    | '/glossary'
    | '/health-benefits'
    | '/how-it-works'
    | '/hvac'
    | '/hvac-applications'
    | '/manage-subscription'
    | '/mold-and-allergens'
    | '/nursery'
    | '/order-history'
    | '/payment-success'
    | '/privacy'
    | '/pro-subscription'
    | '/probiotic-air-purification'
    | '/product-registration'
    | '/product-use-cases'
    | '/proof-and-trust'
    | '/research'
    | '/room-solutions'
    | '/safety'
    | '/shop'
    | '/solutions'
    | '/subscription'
    | '/support'
    | '/terms'
    | '/videos'
    | '/warranty-policy'
    | '/aff/$id'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/compare/bio-healing'
    | '/compare/chemical-fresheners'
    | '/compare/hepa'
    | '/compare/uvc'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AffiliateDashboardRoute: typeof AffiliateDashboardRoute
  AffiliateSignupRoute: typeof AffiliateSignupRoute
  AuthRoute: typeof AuthRoute
  BetterairRebrandRoute: typeof BetterairRebrandRoute
  BlogRoute: typeof BlogRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  CompetitiveExclusionRoute: typeof CompetitiveExclusionRoute
  ContactRoute: typeof ContactRoute
  DormRoute: typeof DormRoute
  EducationRoute: typeof EducationRoute
  EmbedRoute: typeof EmbedRoute
  FaqRoute: typeof FaqRoute
  GlossaryRoute: typeof GlossaryRoute
  HealthBenefitsRoute: typeof HealthBenefitsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  HvacRoute: typeof HvacRoute
  HvacApplicationsRoute: typeof HvacApplicationsRoute
  ManageSubscriptionRoute: typeof ManageSubscriptionRoute
  MoldAndAllergensRoute: typeof MoldAndAllergensRoute
  NurseryRoute: typeof NurseryRoute
  OrderHistoryRoute: typeof OrderHistoryRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  ProSubscriptionRoute: typeof ProSubscriptionRoute
  ProbioticAirPurificationRoute: typeof ProbioticAirPurificationRoute
  ProductRegistrationRoute: typeof ProductRegistrationRoute
  ProductUseCasesRoute: typeof ProductUseCasesRoute
  ProofAndTrustRoute: typeof ProofAndTrustRoute
  ResearchRoute: typeof ResearchRoute
  RoomSolutionsRoute: typeof RoomSolutionsRoute
  SafetyRoute: typeof SafetyRoute
  ShopRoute: typeof ShopRoute
  SolutionsRoute: typeof SolutionsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  VideosRoute: typeof VideosRoute
  WarrantyPolicyRoute: typeof WarrantyPolicyRoute
  AffIdRoute: typeof AffIdRoute
  CompareBioHealingRoute: typeof CompareBioHealingRoute
  CompareChemicalFreshenersRoute: typeof CompareChemicalFreshenersRoute
  CompareHepaRoute: typeof CompareHepaRoute
  CompareUvcRoute: typeof CompareUvcRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty-policy': {
      id: '/warranty-policy'
      path: '/warranty-policy'
      fullPath: '/warranty-policy'
      preLoaderRoute: typeof WarrantyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-solutions': {
      id: '/room-solutions'
      path: '/room-solutions'
      fullPath: '/room-solutions'
      preLoaderRoute: typeof RoomSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-and-trust': {
      id: '/proof-and-trust'
      path: '/proof-and-trust'
      fullPath: '/proof-and-trust'
      preLoaderRoute: typeof ProofAndTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-use-cases': {
      id: '/product-use-cases'
      path: '/product-use-cases'
      fullPath: '/product-use-cases'
      preLoaderRoute: typeof ProductUseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-registration': {
      id: '/product-registration'
      path: '/product-registration'
      fullPath: '/product-registration'
      preLoaderRoute: typeof ProductRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probiotic-air-purification': {
      id: '/probiotic-air-purification'
      path: '/probiotic-air-purification'
      fullPath: '/probiotic-air-purification'
      preLoaderRoute: typeof ProbioticAirPurificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-subscription': {
      id: '/pro-subscription'
      path: '/pro-subscription'
      fullPath: '/pro-subscription'
      preLoaderRoute: typeof ProSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-history': {
      id: '/order-history'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof OrderHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nursery': {
      id: '/nursery'
      path: '/nursery'
      fullPath: '/nursery'
      preLoaderRoute: typeof NurseryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mold-and-allergens': {
      id: '/mold-and-allergens'
      path: '/mold-and-allergens'
      fullPath: '/mold-and-allergens'
      preLoaderRoute: typeof MoldAndAllergensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-subscription': {
      id: '/manage-subscription'
      path: '/manage-subscription'
      fullPath: '/manage-subscription'
      preLoaderRoute: typeof ManageSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac-applications': {
      id: '/hvac-applications'
      path: '/hvac-applications'
      fullPath: '/hvac-applications'
      preLoaderRoute: typeof HvacApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac': {
      id: '/hvac'
      path: '/hvac'
      fullPath: '/hvac'
      preLoaderRoute: typeof HvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-benefits': {
      id: '/health-benefits'
      path: '/health-benefits'
      fullPath: '/health-benefits'
      preLoaderRoute: typeof HealthBenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dorm': {
      id: '/dorm'
      path: '/dorm'
      fullPath: '/dorm'
      preLoaderRoute: typeof DormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitive-exclusion': {
      id: '/competitive-exclusion'
      path: '/competitive-exclusion'
      fullPath: '/competitive-exclusion'
      preLoaderRoute: typeof CompetitiveExclusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betterair-rebrand': {
      id: '/betterair-rebrand'
      path: '/betterair-rebrand'
      fullPath: '/betterair-rebrand'
      preLoaderRoute: typeof BetterairRebrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-signup': {
      id: '/affiliate-signup'
      path: '/affiliate-signup'
      fullPath: '/affiliate-signup'
      preLoaderRoute: typeof AffiliateSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-dashboard': {
      id: '/affiliate-dashboard'
      path: '/affiliate-dashboard'
      fullPath: '/affiliate-dashboard'
      preLoaderRoute: typeof AffiliateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/uvc': {
      id: '/compare/uvc'
      path: '/compare/uvc'
      fullPath: '/compare/uvc'
      preLoaderRoute: typeof CompareUvcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/hepa': {
      id: '/compare/hepa'
      path: '/compare/hepa'
      fullPath: '/compare/hepa'
      preLoaderRoute: typeof CompareHepaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/chemical-fresheners': {
      id: '/compare/chemical-fresheners'
      path: '/compare/chemical-fresheners'
      fullPath: '/compare/chemical-fresheners'
      preLoaderRoute: typeof CompareChemicalFreshenersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/bio-healing': {
      id: '/compare/bio-healing'
      path: '/compare/bio-healing'
      fullPath: '/compare/bio-healing'
      preLoaderRoute: typeof CompareBioHealingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/aff/$id': {
      id: '/aff/$id'
      path: '/aff/$id'
      fullPath: '/aff/$id'
      preLoaderRoute: typeof AffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AffiliateDashboardRoute: AffiliateDashboardRoute,
  AffiliateSignupRoute: AffiliateSignupRoute,
  AuthRoute: AuthRoute,
  BetterairRebrandRoute: BetterairRebrandRoute,
  BlogRoute: BlogRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  CompetitiveExclusionRoute: CompetitiveExclusionRoute,
  ContactRoute: ContactRoute,
  DormRoute: DormRoute,
  EducationRoute: EducationRoute,
  EmbedRoute: EmbedRoute,
  FaqRoute: FaqRoute,
  GlossaryRoute: GlossaryRoute,
  HealthBenefitsRoute: HealthBenefitsRoute,
  HowItWorksRoute: HowItWorksRoute,
  HvacRoute: HvacRoute,
  HvacApplicationsRoute: HvacApplicationsRoute,
  ManageSubscriptionRoute: ManageSubscriptionRoute,
  MoldAndAllergensRoute: MoldAndAllergensRoute,
  NurseryRoute: NurseryRoute,
  OrderHistoryRoute: OrderHistoryRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  ProSubscriptionRoute: ProSubscriptionRoute,
  ProbioticAirPurificationRoute: ProbioticAirPurificationRoute,
  ProductRegistrationRoute: ProductRegistrationRoute,
  ProductUseCasesRoute: ProductUseCasesRoute,
  ProofAndTrustRoute: ProofAndTrustRoute,
  ResearchRoute: ResearchRoute,
  RoomSolutionsRoute: RoomSolutionsRoute,
  SafetyRoute: SafetyRoute,
  ShopRoute: ShopRoute,
  SolutionsRoute: SolutionsRoute,
  SubscriptionRoute: SubscriptionRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  VideosRoute: VideosRoute,
  WarrantyPolicyRoute: WarrantyPolicyRoute,
  AffIdRoute: AffIdRoute,
  CompareBioHealingRoute: CompareBioHealingRoute,
  CompareChemicalFreshenersRoute: CompareChemicalFreshenersRoute,
  CompareHepaRoute: CompareHepaRoute,
  CompareUvcRoute: CompareUvcRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
